server:
  port: 8080

coindesk:
  url: https://min-api.cryptocompare.com
  api_key: 939bec05226ff0969a13ef0e60b6cd76fa08f866e8a3dc41a18362f51ec577f9
  timeout_sec: 10

database:
  url: postgres://macbook@db:5432/crypto?sslmode=disable
cron:
  interval_min: 5