// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/usecase.go

// Package usecase is a generated GoMock package.
package usecase

import (
	entity "final/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPriceRepository is a mock of PriceRepository interface.
type MockPriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPriceRepositoryMockRecorder
}

// MockPriceRepositoryMockRecorder is the mock recorder for MockPriceRepository.
type MockPriceRepositoryMockRecorder struct {
	mock *MockPriceRepository
}

// NewMockPriceRepository creates a new mock instance.
func NewMockPriceRepository(ctrl *gomock.Controller) *MockPriceRepository {
	mock := &MockPriceRepository{ctrl: ctrl}
	mock.recorder = &MockPriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceRepository) EXPECT() *MockPriceRepositoryMockRecorder {
	return m.recorder
}

// GetPrice mocks base method.
func (m *MockPriceRepository) GetPrice(symbol string) (entity.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", symbol)
	ret0, _ := ret[0].(entity.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockPriceRepositoryMockRecorder) GetPrice(symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockPriceRepository)(nil).GetPrice), symbol)
}

// SavePrice mocks base method.
func (m *MockPriceRepository) SavePrice(price entity.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePrice", price)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrice indicates an expected call of SavePrice.
func (mr *MockPriceRepositoryMockRecorder) SavePrice(price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrice", reflect.TypeOf((*MockPriceRepository)(nil).SavePrice), price)
}
